basePath: /api/v1/
definitions:
  models.ConfirmResetPassword:
    properties:
      email:
        type: string
      newPassword:
        type: string
      token:
        type: string
    type: object
  models.EmailCredential:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.ResetPassword:
    properties:
      email:
        type: string
    type: object
  models.Response:
    properties:
      message:
        type: string
    type: object
  models.SignUpModel:
    properties:
      confirmPassword:
        type: string
      dateBirth:
        type: string
      email:
        type: string
      name:
        type: string
      nickname:
        type: string
      password:
        type: string
      zipCode:
        type: string
    type: object
  models.TokenResponse:
    properties:
      accessToken:
        type: string
    type: object
  models.UserVerificationCode:
    properties:
      code:
        type: string
      userId:
        type: integer
    type: object
host: localhost:9090
info:
  contact: {}
  description: REST API for Quebrada Code API
  title: Quebrada Code API
  version: "1.0"
paths:
  /auth/confirm-reset-password:
    post:
      consumes:
      - application/json
      description: reset user password
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ConfirmResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: reset user password
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      tags:
      - Auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: admin sign in
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.EmailCredential'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: admin sign in
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SignUpModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      tags:
      - Auth
  /auth/user-verification:
    post:
      consumes:
      - application/json
      description: Verify user
      parameters:
      - description: Verification Code
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UserVerificationCode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      tags:
      - Auth
swagger: "2.0"
