// // Code generated by Wire. DO NOT EDIT.
//
// //go:generate go run github.com/google/wire/cmd/wire
// //go:build !wireinject
package main

//
//import (
//	"gorm.io/gorm"
//	"quebrada_api/internal/app/controllers"
//	"quebrada_api/ioc"
//)
//
//// Injectors from wire.go:
//
////func InitAuthController(db *gorm.DB) controllers.AuthController {
////	iRepository := ioc.ProvideAuthRepositoryRepostiory(db)
////	authService := ioc.ProvideAuthService(iRepository)
////	authController := ioc.ProvideAuthController(authService)
////	return authController
////}
